# Generated by Django 4.1.2 on 2022-10-11 23:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartMove.category')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SmartMove.exercise')),
                ('completed', models.BooleanField(default=False)),
                ('correctness', models.FloatField(default=0)),
                ('performance', models.FloatField(default=0)),
                ('improvement', models.FloatField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
            ],
            bases=('SmartMove.exercise',),
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('trainee_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartMove.coach')),
                ('assigned_exercises', models.ManyToManyField(to='SmartMove.assignedexercise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('correctness', models.FloatField()),
                ('performance', models.FloatField()),
                ('improvement', models.FloatField()),
                ('calories_burned', models.IntegerField()),
                ('exercises', models.ManyToManyField(to='SmartMove.exercise')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartMove.trainee')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_exercises',
            field=models.ManyToManyField(to='SmartMove.exercise'),
        ),
    ]
